server:
  port: 8080
  #servlet.context-path: /asd  #\u8FFD\u52A0\u9879\u76EE\u8BBF\u95EE\u8DEF\u5F84
#  servlet.context-path: /accesscontrol

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:img/,file:E:/caifu/accesscontrol/file

  datasource:
    url: jdbc:oracle:thin:@192.168.1.230:1521:DQ  #jdbc:oracle:thin:@192.168.1.230:1521:DQ
    username: cf_access
    password: cf_access
    maxPoolSize: 100
    minPoolSize: 5
    #driver-class-name: oracle.jdbc.driver.OracleDriver
  #  datasource:
  #    driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=utf-8&serverTimezone=UTC
  #    username: root
  #    password: root

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
    #\u8BBF\u95EE\u9759\u6001\u8D44\u6E90\u914D\u7F6E


    #mybatis:
    #  mapper-locations: classpath:/mapper/*.xml
    #  configuration:
    #    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

# ping liang ce shi
Image:
  IMAGE_UPLOAD_PATH: /usr/local/tomcat/discountPayImg/
  IMAGE_UPLOAD_BACKUP_PATH: /usr/local/tomcat/discountPayImg/BF
  IMAGE_FILE_PATH: /dynamic
  #  IMAGE_URL_PATH: http://140.207.2.182:6038/projectImage
  IMAGE_URL_PATH: http://testcfpay.caifulife.cn:9330/discountPay
  IMG_PROJECT_PATH: /usr/local/tomcat/discountPayImg/
  IMG_SOCIAL_PATH: http://140.207.2.182:6038/projectImage
  QR_CODE_PATH: http://testcfpay.caifulife.cn:9330/discountPay
  qr_code_path: /usr/local/tomcat/discountPayImg/QR_CODE


# ping liang sheng chan
#IMAGE_UPLOAD_PATH: /usr/local/tomcat/discountPayImg
#IMAGE_UPLOAD_BACKUP_PATH: /usr/local/tomcat/discountPayImg/BF
#IMAGE_FILE_PATH: /dynamic

#IMAGE_URL_PATH: http\://www.caifulife.cn\:210/discountPay
#IMG_PROJECT_PATH: /usr/local/tomcat/discountPayImg

#IMG_SOCIAL_PATH: /usr/local/tomcat/discountPayImg
#QR_CODE_PATH: http\://www.caifulife.cn\:210/discountPay
#qr_code_path: /usr/local/tomcat/discountPayImg/QR_CODE

#\u5206\u9875\u63D2\u4EF6
#pagehelper:
#  helper-dialect: oracle
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
logging:
  level:
    root: error
    com.accesscontrol.manage.mapper: trace
    #    root:
#    com:
#      accesscontrol:
#        manage:
#          controller: info
#          mapper: trace
#    com.accesscontrol.manage.controller: debug
#    com.accesscontrol.manage.mapper: trace
#debug级别 OFF、FATAL、ERROR、WARN、INFO、DEBUG、TRACE

#mybatis-plus:
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 1
#    # Sequence序列接口实现类配置
#    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerato

